CREATE TABLE paper (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    journal VARCHAR(255) NOT NULL,
    file_url VARCHAR(255) NOT NULL
);
